import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { AiService } from '../../ai/ai.service';
import { TrainingPlan, Team, Match } from '../entities';
import { GenerateTrainingInput } from '../dto';

@Injectable()
export class TrainingGeneratorService {
  private readonly logger = new Logger(TrainingGeneratorService.name);

  constructor(
    @InjectRepository(TrainingPlan)
    private trainingRepository: Repository<TrainingPlan>,
    @InjectRepository(Team)
    private teamRepository: Repository<Team>,
    @InjectRepository(Match)
    private matchRepository: Repository<Match>,
    private aiService: AiService,
  ) {}

  async generateTrainingPlan(
    userId: string,
    input: GenerateTrainingInput,
  ): Promise<TrainingPlan> {
    this.logger.log(`Generating training plan for team ${input.teamId}`);

    // Load team
    const team = await this.teamRepository.findOne({
      where: { id: input.teamId, userId },
      relations: ['players'],
    });

    if (!team) {
      throw new Error('Team not found');
    }

    // Load match if specified
    let matchContext = null;
    if (input.basedOnMatchId) {
      const match = await this.matchRepository.findOne({
        where: { id: input.basedOnMatchId, userId },
        relations: ['analyses', 'events'],
      });
      matchContext = match;
    }

    // Build prompt
    const prompt = this.buildTrainingPrompt(team, input, matchContext);

    // Call AI
    const aiResponse = await this.aiService.chat(userId, null, prompt, {
      systemPrompt: this.getTrainingSystemPrompt(),
      temperature: 0.8,
      maxTokens: 3000,
    });

    // Parse AI response
    const trainingData = this.parseTrainingResponse(aiResponse.content, input);

    // Create training plan
    const training = this.trainingRepository.create({
      userId,
      teamId: input.teamId,
      title: trainingData.title,
      description: trainingData.description,
      targetDate: new Date(),
      duration: input.duration,
      focus: input.focus,
      difficulty: input.difficulty || 'medium',
      objectives: trainingData.objectives,
      weaknesses: trainingData.weaknesses,
      exercises: trainingData.exercises,
      warmUp: trainingData.warmUp,
      coolDown: trainingData.coolDown,
      crossSportInnovation: trainingData.crossSportInnovation,
      targetPlayers: trainingData.targetPlayers,
      expectedOutcomes: trainingData.expectedOutcomes,
      physicalLoad: trainingData.physicalLoad,
      status: 'planned',
      notes: `Generated by FootMind Engine AI\n\n${aiResponse.content}`,
    });

    return await this.trainingRepository.save(training);
  }

  private getTrainingSystemPrompt(): string {
    return `
Tu es un expert en préparation physique et tactique pour le football.
Tu combines les meilleures pratiques du football moderne avec des innovations
du basket, handball, rugby et NFL.

Tu génères des plans d'entraînement complets, structurés et adaptés aux besoins spécifiques.
Tes entraînements sont scientifiques, progressifs et focalisés sur les objectifs.
`;
  }

  private buildTrainingPrompt(
    team: Team,
    input: GenerateTrainingInput,
    matchContext: any,
  ): string {
    let prompt = `Génère un plan d'entraînement complet pour l'équipe "${team.name}".\n\n`;

    prompt += `**Paramètres**:\n`;
    prompt += `- Durée: ${input.duration} minutes\n`;
    prompt += `- Focus: ${input.focus}\n`;
    prompt += `- Difficulté: ${input.difficulty || 'medium'}\n`;
    prompt += `- Nombre de joueurs: ${team.players?.length || 'inconnu'}\n`;
    prompt += `- Style tactique équipe: ${team.tacticalStyle || 'non défini'}\n`;
    prompt += `- Formation: ${team.formation || 'non définie'}\n\n`;

    if (input.targetWeaknesses && input.targetWeaknesses.length > 0) {
      prompt += `**Faiblesses à cibler**:\n`;
      input.targetWeaknesses.forEach((w) => {
        prompt += `- ${w}\n`;
      });
      prompt += `\n`;
    }

    if (matchContext) {
      prompt += `**Basé sur le match précédent**:\n`;
      prompt += `- ${matchContext.homeTeam?.name || 'Home'} vs ${matchContext.awayTeam?.name || 'Away'}\n`;
      prompt += `- Score: ${matchContext.homeScore}-${matchContext.awayScore}\n`;
      if (matchContext.analyses?.length > 0) {
        prompt += `- Analyse disponible avec faiblesses et recommandations\n`;
      }
      prompt += `\n`;
    }

    if (input.specificObjectives) {
      prompt += `**Objectifs spécifiques**: ${input.specificObjectives}\n\n`;
    }

    prompt += `Fournis un plan d'entraînement structuré incluant:\n\n`;
    prompt += `1. **Titre et description** du plan\n`;
    prompt += `2. **Objectifs** (3-5 objectifs avec priorités)\n`;
    prompt += `3. **Échauffement** (10-15 min)\n`;
    prompt += `4. **Exercices principaux** (détaillés):\n`;
    prompt += `   - Nom de l'exercice\n`;
    prompt += `   - Type (drill, rondo, scrimmage, conditioning, etc.)\n`;
    prompt += `   - Durée\n`;
    prompt += `   - Intensité\n`;
    prompt += `   - Description complète\n`;
    prompt += `   - Setup et organisation\n`;
    prompt += `   - Points de coaching\n`;
    prompt += `   - Variations possibles\n`;
    prompt += `   - Équipement nécessaire\n`;
    prompt += `5. **Retour au calme** (5-10 min)\n`;
    prompt += `6. **Charge physique estimée** (distance, sprints, calories)\n`;
    prompt += `7. **Résultats attendus**\n`;

    if (input.includeCrossSportDrills) {
      prompt += `8. **Innovations cross-sport** (basket, handball, rugby, NFL)\n`;
      prompt += `   - Sport d'origine\n`;
      prompt += `   - Drill adapté\n`;
      prompt += `   - Bénéfice attendu\n`;
    }

    prompt += `\nRéponds de manière très structurée et détaillée en format JSON.`;

    return prompt;
  }

  private parseTrainingResponse(aiResponse: string, input: GenerateTrainingInput): any {
    // Try to parse JSON first
    try {
      const jsonMatch = aiResponse.match(/```json\s*([\s\S]*?)\s*```/);
      if (jsonMatch) {
        return JSON.parse(jsonMatch[1]);
      }
    } catch (e) {
      this.logger.warn('Failed to parse JSON from AI response, using fallback parsing');
    }

    // Fallback: manual parsing
    const result: any = {
      title: `${input.focus.charAt(0).toUpperCase() + input.focus.slice(1)} Training - ${input.duration}min`,
      description: '',
      objectives: [],
      weaknesses: [],
      exercises: [],
      warmUp: { duration: 15, exercises: [] },
      coolDown: { duration: 10, exercises: [] },
      crossSportInnovation: [],
      targetPlayers: [],
      expectedOutcomes: [],
      physicalLoad: {
        expectedDistance: Math.floor(input.duration / 10), // rough estimate: 1km per 10min
        expectedSprints: Math.floor(input.duration / 5),
        expectedHighIntensityRuns: Math.floor(input.duration / 3),
        estimatedCalories: input.duration * 8, // rough estimate
      },
    };

    // Extract description (first paragraph)
    const descMatch = aiResponse.match(/(?:Description|Titre)[:\s]+([^\n]+(?:\n(?![#*-])[^\n]+)*)/i);
    if (descMatch) {
      result.description = descMatch[1].trim();
    }

    // Extract objectives
    const objMatch = aiResponse.match(/(?:Objectifs|Objectives)[:\s]+([\s\S]+?)(?=\n#|\n\*\*|\n\d+\.)/i);
    if (objMatch) {
      const objLines = objMatch[1].match(/[-•]\s*(.+)/g) || [];
      result.objectives = objLines.slice(0, 5).map((line) => ({
        objective: line.replace(/^[-•]\s*/, '').trim(),
        priority: 'medium',
      }));
    }

    // Extract exercises from numbered or bulleted list
    const exerciseMatches = aiResponse.matchAll(/(?:^|\n)(?:\d+\.|[-•])\s*\*\*(.+?)\*\*[:\s]*([^\n]+(?:\n(?![-•\d])[^\n]+)*)/gim);
    for (const match of exerciseMatches) {
      result.exercises.push({
        name: match[1].trim(),
        type: 'drill',
        duration: Math.floor(input.duration / 4), // split equally
        intensity: input.difficulty === 'high' ? 'high' : 'medium',
        description: match[2].trim(),
        setup: '',
        coachingPoints: [],
        variations: [],
        equipment: [],
        playersCount: 10,
        spaceRequired: 'half-pitch',
      });
    }

    // Ensure at least 2 exercises
    if (result.exercises.length < 2) {
      result.exercises.push({
        name: `${input.focus} Drill 1`,
        type: 'drill',
        duration: Math.floor(input.duration / 2),
        intensity: 'medium',
        description: 'Focus on fundamental skills and team coordination',
        setup: 'Organize players in small groups',
        coachingPoints: ['Maintain intensity', 'Focus on technique'],
      });
    }

    return result;
  }

  async updateTrainingPlan(
    userId: string,
    planId: string,
    updates: Partial<TrainingPlan>,
  ): Promise<TrainingPlan> {
    const plan = await this.trainingRepository.findOne({
      where: { id: planId, userId },
    });

    if (!plan) {
      throw new Error('Training plan not found');
    }

    Object.assign(plan, updates);
    return await this.trainingRepository.save(plan);
  }

  async completeTrainingPlan(
    userId: string,
    planId: string,
    feedback: string,
    actualMetrics: any,
  ): Promise<TrainingPlan> {
    const plan = await this.trainingRepository.findOne({
      where: { id: planId, userId },
    });

    if (!plan) {
      throw new Error('Training plan not found');
    }

    plan.status = 'completed';
    plan.feedback = feedback;
    plan.actualMetrics = actualMetrics;

    return await this.trainingRepository.save(plan);
  }
}
